"use client"

import useDocumentTitle from "../hooks/useDocumentTitle"

export default function TermsAndConditions() {
    useDocumentTitle("Terms & Conditions - TruthSeeker")

    return (
        <div className="relative z-10 min-h-screen px-6 md:px-20 py-32 font-turret-road text-[#e0e9f6]">
            <div className="max-w-3xl mx-auto space-y-6">
                <h1 className="text-4xl font-bold text-white">Terms &amp; Conditions</h1>
                <p className="text-sm text-[#8db5de]">Last updated: {new Date().toLocaleDateString()}</p>

                <p>
                    TruthSeeker is a student project, not a professional fact-checking service. By using it,
                    you agree to the following.
                </p>

                <h2 className="text-2xl font-bold text-white pt-4">No guarantee of accuracy</h2>
                <p>
                    Verdicts are generated by an AI pipeline combining a fine-tuned classifier, retrieved
                    evidence, and a large language model. Results can be wrong, incomplete, or outdated.
                    Do not treat any result as a definitive or professional fact-check. Always verify
                    important claims through additional, authoritative sources.
                </p>

                <h2 className="text-2xl font-bold text-white pt-4">Your account</h2>
                <p>
                    You're responsible for keeping your login credentials secure and for the claims you
                    submit. Don't use the service to generate or spread harmful, illegal, or abusive content.
                </p>

                <h2 className="text-2xl font-bold text-white pt-4">Availability</h2>
                <p>
                    This is a personal project run on free-tier infrastructure. It may be slow, rate-limited,
                    or occasionally unavailable, and features may change without notice.
                </p>

                <h2 className="text-2xl font-bold text-white pt-4">Contact</h2>
                <p>Questions can be sent to dmunmun260@gmail.com.</p>
            </div>
        </div>
    )
}
